### ISSUE TITLE
J7+ Integration 

### ISSUE THREAD

**Issue by jorishorizon** [jeremywillans/lovelace-roomba-vacuum-card#8]
I was able to add the new J7+ Roomba Irobot to home assistant via an IOS app Thor that was able to get the password because this version is missing a home button to generate the password. 
When I add the password it is connected but only showing Status: Docked or something else. The other parts are not unavailable: like, mode, battery, cleanbase etc. You are able to press play and to pause and bring the robot Home but the main display is showing unavailable. Is there someone able to fix this? Do you need more input from my side? 
![image](https://user-images.githubusercontent.com/6254056/139961141-254daf3e-7acb-464c-bf1f-db0f47055648.png)
new: picture for j7+ 
![vacuum](https://user-images.githubusercontent.com/6254056/139961183-2aa8bad0-1bf0-4e38-9937-e4c5d740b667.png)

**Comment by jeremywillans** [comment]
Try setting [this](https://github.com/koalazak/dorita980/issues/142#issuecomment-950402865) ENV Variable for the rest980 container and see if any better information is returned

**Comment by mehalter** [comment]
@jorishorizon thanks for providing a new image for the J7 card. Not sure if this is a good place to put this information since it pertains more to the ha-rest980-roomba repo (figured it would be most useful along with the background), but I wanted went ahead and made new assets for the mapping display as well. Also should note that this is not particularly useful at the moment since the latest firmwares remove the position reporting, but hopefully that gets fixed at some point and these images can be of use to people.

![roomba](https://user-images.githubusercontent.com/1591837/149566838-a81c120b-f99f-4a16-b517-39c1070f3a8a.png)
![roomba_charging](https://user-images.githubusercontent.com/1591837/149566852-e076c0a4-282c-4635-881e-c24a1495de6d.png)
![roomba_stuck](https://user-images.githubusercontent.com/1591837/149566854-ad97715d-c3a8-4145-94d8-226fbfc96e4a.png)

**Comment by sbuell1** [comment]
@jorishorizon were you able to get this running correctly? I’m stuck trying to retrieve my password via Thor. Not sure where to look in the logs. 
![Uploading 4CD2C037-BB7D-4F7C-83AF-BBF22A3925D4.png…]()

**Comment by jorishorizon** [comment]
Hi. I also had issue finding the password. Schroll until you find this link
/v2/login
Below this link you see in green:
Post ->.json
Press this green: other screen will open and scroll down to find your password.

hope this works.

**Comment by jeremywillans** [comment]
@jorishorizon - did you happen to get this setup working with a j7 ? Does selective cleaning work as expected?

**Comment by richard-collier** [comment]
I am having the same issues with an i3 EVO.
